apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - name: app
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: server
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gateway
  type: ClusterIP
