apiVersion: skaffold/v2beta1
kind: Config
deploy:
  kustomize:
    paths:
    - ./kube/skaffold
profiles:
- name: dev
  build:
    artifacts:
    - image: righm9/echo
      bazel:
        target: //echo:image.tar
    - image: righm9/gateway
      bazel:
        target: //gateway:image.tar
    local:
      push: false
      useBuildkit: true
  activation:
  - command: dev
